services:
    database:
        image: postgres:15
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}

    migrations:
        build: ./migrations
        depends_on:
            - database
        environment:
            - DATABASE_URL=${DATABASE_URL}

    node-app:
        build:
            context: ./node-app
            dockerfile: Dockerfile.prod
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - database

    go-app:
        build:
            context: ./go-app
            dockerfile: Dockerfile.prod
        working_dir: /app
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - database
    rust-app:
        build:
            context: ./rust-app
            dockerfile: Dockerfile.prod
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - database
