services:
    database:
        image: postgres:15
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
          - "5432:5432"

    migrations:
        build: ./migrations
        depends_on:
            - database
        env_file:
            - .env.development
        ports:
          - "5555:5555"
        volumes:
          - ./migrations/prisma:/app/prisma

    node-app:
        build: ./node-app
        env_file:
            - .env.development
        depends_on:
            - database
        ports:
          - "7070:7070"
        volumes:
          - ./node-app:/app
