# ===== Build Stage =====

FROM golang:1.24.3 AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-s -w" -o server src/server.go

# ===== Production Stage =====

FROM debian:bookworm
COPY --from=builder /app/server /server
CMD ["/server"]

EXPOSE 8080
