# ===== Build Stage =====

FROM rust:1.88.0 AS builder

WORKDIR /app

COPY . .

RUN cargo build --release

# ===== Production Stage =====

FROM debian:bookworm

COPY --from=builder /app/target/release/rust-app /rust-app

CMD ["/rust-app"]

EXPOSE 9090

